### ISSUE TITLE
Suggestion: pull species and thumbnail position information from the description or tags instead of title.

### ISSUE THREAD

**Issue by fortepc** [jamiehumphries/photodex#2]
Problem to solve: 
Readability of Titles if browsing from within Flickr

Possible Solution:
Pull information like which species it is, and what position the thumbnail should be from the tags of a photo instead of the title. 

Alternate Solution: 
Pull from the description instead.

Side effect benefits: 
Allowing the user to have a creative titles for their images that could show up inside of their PhotoDex.

**Comment by fortepc** [comment]
Further: Could also be used to determine which is the thumbnail image for that species, allowing the Flickr album to be sorted by date taken, so browsing through flickr is like following your journey in order, where browsing via photodex is browsing my species.

**Comment by jamiehumphries** [comment]
Unfortunately, the description of the photo is not returned in the API method to list all photos in a set: https://www.flickr.com/services/api/flickr.photosets.getPhotos.html

To get the description you need to make an additional API call, which would be too expensive to do per photo.

I will look in to doing this via tags, but my initial concern around that approach was that it is not the intention of Flickr tagging and would result in your photos ending up in weird tag searches.

**Comment by jamiehumphries** [comment]
Oh yeah, I remember the problem with tags now. For some reason, anyone is allowed to add tags to public photos on Flickr! So it is open for unintended problems as a result.

I will look into other solutions for this, but I think the metadata may have to stay in the title.

The thumbnail suggestion is a slightly different concern. I will consider other ways to approach this.

**Comment by jamiehumphries** [comment]
Closing this as a "won't fix".
