### ISSUE TITLE
Suggestion: Pull trainer metadata from Album Description

### ISSUE THREAD

**Issue by fortepc** [jamiehumphries/photodex#3]
I had to use an alternate name on my Flickr account (Trainer_Forte) than I use in Pogo (Forte), and would like my photodex to show my actual trainer name, and maybe even link my photodex to my [Traveler Card](http://sil.ph/forte) in my photodex

ie: 
`trainername:forte`
`silph:forte`

**Comment by jamiehumphries** [comment]
Good idea. I will add this.

**Comment by jamiehumphries** [comment]
I have added this feature for trainer names and updated the instructions on the homepage.

For now I have not added a link to The Silph Road, but may look into that in the future. Please raise a separate issue for that if you want.
