### ISSUE TITLE
Bug: Seemingly random highlights of species numbers

### ISSUE THREAD

**Issue by fortepc** [jamiehumphries/photodex#4]
When browsing my Photodex, https://www.photodex.io/Trainer_Forte, some dex numbers, like 172-175 have a different highlight than the rest of the dex numbers.

**Comment by jamiehumphries** [comment]
This is to represent Pokémon for which it is impossible to get an AR snap. For example, 172-175 are baby Pokémon that can only be hatched. I will add some title text to explain this on hover.

**Comment by jamiehumphries** [comment]
Hmm, actually I don't really like the hover text. It's a bit distracting.

If you have another suggestion for the UX here please let me know!

**Comment by fortepc** [comment]
Maybe... 

Clicking on pokemon spots that don't have a picture opens a little dialogue instead of being hover text. Click on a normal blank space, and it says "this photo is missing from this photodex" or something and on unobtainable ones it says "This pokemon doesn't currently spawn in the wild, so AR photos are unobtainable for this species"

**Comment by jamiehumphries** [comment]
I don't much like that idea, sorry. I'm going to leave this one unchanged for now.
