### ISSUE TITLE
Suggestion: Link to external sources for Trainer metadata

### ISSUE THREAD

**Issue by fortepc** [jamiehumphries/photodex#5]
Trainerdex and silphroad traveler cards are both great hooks for a trainer's profile. It would be cool if a trainer could add links to their profiles on those websites in order to link their metadata to it. Linking to those locations would also allow you to pull metadata from that trainer if you wanted to display their trainer level or their location or their actual Pokedex statistics compared to their photodex statistics. 

Will mock-up something basic as an example of how I think it could look and post to this issue in the next day or so.

**Comment by jamiehumphries** [comment]
In the absence of any mock ups from you I am going to close this. Feel free to create a pull request if you ever manage to get something working yourself.
