### ISSUE TITLE
Request For Logo / Thumbnail

### ISSUE THREAD

**Issue by dandesousa** [jamiehumphries/photodex#6]
Hey I would love to add support in PokeNav to link to a users PhotoDex profile. I would also love to link to it in the mobile app. 

As part of that support, is there a logo or other brand image you'd like for me to display alongside when possible?

**Comment by jamiehumphries** [comment]
Hi @dandesousa. I just use the camera icon from Pokémon GO as my favicon, so I don't really have a logo. If you want to use that then this is the best version I have: 
![camera.png](https://user-images.githubusercontent.com/3533273/46878135-656f0600-ce3a-11e8-9b37-7165dde6922d.png)
Is there anything else that you need from me?

**Comment by dandesousa** [comment]
Should be all -- I'm actually being overly paranoid and avoiding any use of the game assets in the app -- so if its OK with you I will use a styled vector icon for a camera?

If thats ok thats really all I need!

**Comment by jamiehumphries** [comment]
Sure whatever you prefer. 🙂

**Comment by jamiehumphries** [comment]
@dandesousa, is this the sort of integration that you are planning with Photódex? https://pokenavbot.com/#integrations
If so, let me know and I can add an API for the bits that you want.

**Comment by dandesousa** [comment]
I would totally add anything you want to support -- initially I was just going to add a url link to photo dex -- maybe have a command that lets you quickly embed a photo of a pokemon 

`$photodex charmander` grabs your charmander photo if linked and drops it into discord.

Don't think I necessarily need anything from you for that as I should be able to infer everything from the national dex number right

**Comment by jamiehumphries** [comment]
@dandesousa I have added a basic JSON API endpoint for you to pull through the information about an individual's Photódex.

The end point is: `https://www.photodex.io/api/trainer/<flickr_user_name>`
For example: https://www.photodex.io/api/trainer/JTAtomico

I haven't documented it yet, but hopefully it is self-explanatory! Feel free to ask any questions that you may have.
